import Head from "next/head";
import styles from "../styles/Home.module.css";

import { loadTossPayments } from "@tosspayments/payment-sdk";
import { useEffect } from "react";
const clientKey = "test_ck_OyL0qZ4G1VOKj27DjXMVoWb2MQYg";

export default function Home() {
  useEffect(() => {
    // onPay();
  }, []);

  const onPay = async () => {
    try {
      const tossPayments = await loadTossPayments(clientKey);

      const res = await tossPayments.requestPayment("카드", {
        amount: 15000,
        orderId: "yru1QbazafgqfHjk-edE5",
        orderName: "토스 티셔츠 외 2건",
        customerName: "박토스",
        successUrl: "http://localhost:8081/success",
        failUrl: "http://localhost:8081/fail",
        flowMode: "DIRECT",
        easyPay: "토스페이", // 페이코 / PAYCO | 카카오페이 / KAKAOPAY | 네이버페이 / NAVERPAY
      });

      console.log("res: ", res);
    } catch (error) {
      console.log("error: ", error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button className={styles.title} onClick={onPay}>
          Payment
        </button>
      </main>
    </div>
  );
}
